repos:
  - repo: local
    hooks:
      - id: header-context
        name: Header Context
        entry: python -m header_context
        language: system
        types: [python]
        
      - id: black
        name: black
        entry: python -m black .
        language: system
        types: [python]

      - id: pylint
        name: pylint
        entry: python -m pylint src --disable=import-error
        language: system
        types: [python]